Update main.py
ImportError: cannot import name 'Level' from partially initialized module 'level' (most likely due to a circular import) (/Users/michaelsau/Desktop/make-project-Master 2/Code/level.py)

Keep running into this error, trying to figure out what it is